### ISSUE TITLE
ReferenceError on `require`

### ISSUE THREAD

**Issue by NickHeiner** [ileri/l-system#2]
When I `require` this repo, I get an error:

```
~/public-repos/l-system <master> λ node
> require('./')
ReferenceError: regeneratorRuntime is not defined
    at /Users/nick.heiner/public-repos/l-system/dist/l-system.js:174:12
    at Object.<anonymous> (/Users/nick.heiner/public-repos/l-system/dist/l-system.js:215:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:133:27)
> 

```

I inspect the `dist/l-system.js`, and I do see `regeneratorRuntime` being referenced, but I'm not sure where it is supposed to be defined.

**Comment by NickHeiner** [comment]
This is fixed by #3.
